// ============================================================
// Реестр команд: номер стола -> название команды.
// Заполняется оргами заранее, тянется в форму записи автоматически.
// ============================================================

const teams = [
  { table: 1, team: "AutoMates" },
  { table: 2, team: "Атланты" },
  { table: 3, team: "Вайбкрафт" },
  { table: 4, team: "felis_kaktus" },
  { table: 5, team: "Connectome" },
  { table: 6, team: "Токеноукладчики" },
  { table: 7, team: "DBA PLUS" },
  { table: 8, team: "Aleksanya Invest" },
  { table: 9, team: "ДАП" },
  { table: 10, team: "IpingWin" },
  { table: 11, team: "Data361" },
  { table: 12, team: "ИИчница" },
  { table: 13, team: "Зеленый ящик" },
  { table: 14, team: "Пять вентиляторов" },
  { table: 15, team: "Уважаемые Коллеги" },
  { table: 16, team: "Dreamteam SberUser" },
  { table: 17, team: "headless software engineers (HSE" },
  { table: 18, team: "Горыныч" },
  { table: 19, team: "CleverCore" },
  { table: 20, team: "Джинсоны" },
  { table: 21, team: "SberGroup" },
  { table: 22, team: "Pandas" },
  { table: 23, team: "НИВА" },
  { table: 24, team: "PumpDLC" },
  { table: 25, team: "Skill Issue" },
  { table: 26, team: "5 промптов до продакшена" },
  { table: 27, team: "Мертвые души" },
  { table: 28, team: "ЯМыЕгор" },
  { table: 29, team: "Красного знаменИИ" },
  { table: 30, team: "Белоснежка ИИ гномы" },
  { table: 31, team: "PADATA Портфельная Аналитика" },
  { table: 32, team: "Команда номер 1" },
  { table: 33, team: "AI Alchemists" },
  { table: 34, team: "GigaCourme" },
  { table: 35, team: "Phygital AI winners" },
  { table: 36, team: "Переводилки" },
  { table: 37, team: "AI как просто" },
  { table: 38, team: "Пираты Силиконовой долины" },
  { table: 39, team: "УДКЗ" },
  { table: 40, team: "NeuroNinjas" },
  { table: 41, team: "Четыредевятки" },
  { table: 42, team: "Надежда Бобров" },
  { table: 43, team: "Core" },
  { table: 44, team: "Qwerty" },
  { table: 45, team: "ex-YellowSubMarine" },
  { table: 46, team: "TakeITEasy" },
  { table: 47, team: "DropApp MGMT" },
  { table: 48, team: "Summary & Action Agent" },
  { table: 49, team: "Агент 67" },
  { table: 50, team: "АИ-95 до полного" },
  { table: 51, team: "VED DEV" },
  { table: 52, team: "Core Banking Customs" },
  { table: 53, team: "ИнфраМон" },
  { table: 54, team: "No humans in loop" },
  { table: 55, team: "Костыльное агентство" },
  { table: 56, team: "AI Panic" },
  { table: 57, team: "Одна рельса и три шпалы" },
  { table: 58, team: "null" },
  { table: 59, team: "Ждем токены" },
  { table: 60, team: "Агенты Надежности" },
  { table: 61, team: "Snatch" },
  { table: 62, team: "Бэки в стеке" },
  { table: 63, team: "Corai" },
  { table: 64, team: "соджа" },
  { table: 65, team: "Прожигатели токенов" },
  { table: 66, team: "APEs" },
  { table: 67, team: "FinAI" },
  { table: 68, team: "GigaHolmes" },
  { table: 69, team: "Bug Busters" },
  { table: 70, team: "Циклопы" },
  { table: 71, team: "Moscow Matrix" },
  { table: 72, team: "AiTestUtil" },
  { table: 73, team: "MC P" },
  { table: 74, team: "GGnext" },
  { table: 75, team: "OuroBotics" },
  { table: 76, team: "АИД" },
  { table: 77, team: "Расчеты с МФ" },
  { table: 78, team: "Агенты Смита" },
  { table: 79, team: "TechAI" },
  { table: 80, team: "demonic arrays" },
  { table: 81, team: "Может, сработает" },
  { table: 82, team: "Сберпечать" },
  { table: 83, team: "BandAI" },
  { table: 84, team: "Десакуа" },
  { table: 85, team: "Тягач" },
  { table: 86, team: "SberNova" },
  { table: 87, team: "Андрей и 5 якорей" },
  { table: 88, team: "AI-Kassa 2.0" },
  { table: 89, team: "ИЦР" },
  { table: 90, team: "ХХХ" },
  { table: 91, team: "DIТоксики" },
  { table: 92, team: "GateKeepers" },
  { table: 93, team: "QuantumDot" },
  { table: 94, team: "Пиши нормально" },
  { table: 95, team: "Капельки" },
  { table: 96, team: "Барабульки" },
  { table: 97, team: "Tempo" },
  { table: 98, team: "Token Rebels" },
  { table: 99, team: "morj request" },
  { table: 100, team: "[КБ] ПКБ х СКИФ" },
  { table: 101, team: "ЗарплаткаМэн" },
  { table: 102, team: "ИнциДень" },
  { table: 103, team: "Капибарайтинг" },
  { table: 104, team: "OPKC" },
  { table: 105, team: "Kirpich Crew" },
  { table: 106, team: "ТехноЭскадра" },
  { table: 108, team: "Канбанчики" },
  { table: 109, team: "opeshki" },
  { table: 110, team: "Вжух" },
  { table: 111, team: "Эвалюшн" },
  { table: 114, team: "FinOuroBros" },
  { table: 115, team: "Серпенс" },
  { table: 118, team: "Иван Васильевич меняет промт" },
  { table: 119, team: "DevMind" },
  { table: 122, team: "SWAGa Team" },
  { table: 123, team: "Фронт-Пираты" },
  { table: 125, team: "Фиксики" },
  { table: 126, team: "Головастики" },
];

module.exports = { teams };
